export const SUPER_ADMIN_ROUTES = {
  login: '/super-admin/login',
  home: '/super-admin',
  dashboard: '/super-admin/dashboard',
  settings: '/super-admin/settings',
  partnerManagement: '/super-admin/partner-management',
  orderManagement: '/super-admin/order-management',
  eachOrder: '/super-admin/order-management/',
  eachOrderID: '/super-admin/order-management/:id',
  customer: '/super-admin/customer',
  customerDetails: '/super-admin/customer/',
  customerDetailsID: '/super-admin/customer/:id',
  customerActivityLog: '/super-admin/customer/activity-log/',
  customerActivityLogID: '/super-admin/customer/activity-log/:id',
  addPartner: '/super-admin/partner-management/add',
  partnerDetail: '/super-admin/partner-management/',
  partnerDetailID: '/super-admin/partner-management/:id',
  inventory: '/super-admin/inventory',
  eachProduct: '/super-admin/inventory/',
  addProduct: '/super-admin/inventory/add',
  eachProductID: '/super-admin/inventory/:id',
  productActivityLog: '/super-admin/inventory/activity-log/',
  productActivityLogID: '/super-admin/inventory/activity-log/:id',
  editEachProduct: '/super-admin/inventory/edit/',
  editEachProductID: '/super-admin/inventory/edit/:id',
  transactions: '/super-admin/transactions',
  analytics: '/super-admin/analytics',
  // add other routes as needed
};

export const SUPER_ADMIN_PROTECTED_ROUTES = [
  SUPER_ADMIN_ROUTES.home,
  SUPER_ADMIN_ROUTES.dashboard,
  SUPER_ADMIN_ROUTES.settings,
  SUPER_ADMIN_ROUTES.partnerManagement,
  SUPER_ADMIN_ROUTES.orderManagement,
  SUPER_ADMIN_ROUTES.customer,
  SUPER_ADMIN_ROUTES.addPartner,
  SUPER_ADMIN_ROUTES.partnerDetailID,
  SUPER_ADMIN_ROUTES.inventory,
  SUPER_ADMIN_ROUTES.eachProduct,
  SUPER_ADMIN_ROUTES.addProduct,
  SUPER_ADMIN_ROUTES.eachProductID,
  SUPER_ADMIN_ROUTES.editEachProduct,
  SUPER_ADMIN_ROUTES.editEachProductID,
  SUPER_ADMIN_ROUTES.transactions,
  SUPER_ADMIN_ROUTES.analytics,
  SUPER_ADMIN_ROUTES.eachOrder,
  SUPER_ADMIN_ROUTES.eachOrderID,
  SUPER_ADMIN_ROUTES.customerDetails,
  SUPER_ADMIN_ROUTES.customerDetailsID,
  SUPER_ADMIN_ROUTES.customerActivityLog,
  SUPER_ADMIN_ROUTES.customerActivityLogID,
  SUPER_ADMIN_ROUTES.productActivityLog,
  SUPER_ADMIN_ROUTES.productActivityLogID,
];
