// Base URL for your frontend app pages visited by Cypress (e.g. /login, /sign-up).
const WEB_BASE_URL =
    typeof Cypress !== "undefined" && Cypress.config("baseUrl")
        ? Cypress.config("baseUrl")
        : "http://localhost:3000";
// Base URL for your backend API used by app requests (staging by default fallback).
const API_BASE_URL =  "https://staging-api.sendsile.com/api/v1"

// Route path for login page and login API intercept pattern.
const LOGIN_PATH = "/login"
// Route path for sign-up page.
const SIGNUP_PATH = "/sign-up"
// Route path for create-password page.
const CREATE_PASSWORD_PATH = "/create-password"
// Route path for forgot-password page.
const FORGOT_PASSWORD_PATH = "/forgot-password"
// Route path for email verification instruction page.
const EMAIL_VERIFICATION_PATH = "/email-verification"
// Route path template for email verification link with params.
const EMAIL_VERIFICATION_TOKEN_PATH = "/email-verification/:token/:id"
// API path used for register endpoint intercepts.
const REGISTER_API_PATH = "/register"
// API path used for forgot-password reset-initiate intercepts.
const RESET_INITIATE_API_PATH = "/password/reset/initiate"
// API path used for resend verification email intercepts.
const RESEND_EMAIL_API_PATH = "/email/resend"

export const Sendsile = {
    login: {
        pageUrl: `${WEB_BASE_URL}${LOGIN_PATH}`,
        base: API_BASE_URL,
        path: LOGIN_PATH,
        emailId: "#email",
        message01: "Login to your account",
        emailentry: "hello@test.com",
        passwordentry: "mypassword",
        message02:"Forgot password?",
        message03:"Continue with google",
        message04:"Invalid credentials",
        wrongemail:"wrong@example.com",
        wrongpassword:"wrongpassword",
        button:"Continue",
        statuscode: 200,
        statuscodefail: 400,
        testemail:"user@example.com",
        testname:"Test User",
        testbalance:0,
        testphone:"0000000000",
        photo:"",
        temp_token:"temp-2fa-token",
        loginUrl:"/login",
        login2faUrl:"/login/2fa",
        loginmessage01:"OTP",
        loginmessage02:"OTP sent to your email",
        loginemail:"user@example.com",
        loginpassword:"Password123",
        loginmessage03:"Invalid OTP",
        instructionmessage01:"Enter 6-digit code on your Authenticator App",
    },
    signup: {
        pageUrl: `${WEB_BASE_URL}${SIGNUP_PATH}`,
        base: API_BASE_URL,
        message01: "Let's sign you up first",
        nameId: "#fullname",
        emailId: "#email",
        passwordId: "#password",
        confirmPassword: "confirmPassword",
        button: "Continue",
        statuscode: 200,
        responsemail: "user@example.com",
        message02: "Passwords do not match",
        registerURL: REGISTER_API_PATH,
        message03: "Successfully filled vailable form fields",
        statuscodefail: 400,
        waitcode: 3000,
        message04: "Login link found",
        emailURL: EMAIL_VERIFICATION_PATH,
    },
    emailVerification: {
        pageUrl: `${WEB_BASE_URL}${EMAIL_VERIFICATION_PATH}`,
        verifyUrl: `${WEB_BASE_URL}/email-verification/test-token/123?signature=abc&expires=1`,
        base: API_BASE_URL,
        header01: "Check your inbox",
        header02: "A verification email has been sent to your email",
        resendButton: "Resend verification email",
        resendmessage01: "Verification email resent",
        resenderror: "Unable to resend verification email",
        resendUrl:"/email/verify/test-token/123?signature=abc&expires=1",
        resendmessage02:"Email verified",
        resendendpoint: RESEND_EMAIL_API_PATH,
        verifyendpoint: "/email/verify/test-token/123?*",
        statuscode: 200,
        statuscodefail: 400,

    },
    forgotpassword:{
        pageUrl: `${WEB_BASE_URL}${FORGOT_PASSWORD_PATH}`,
        base: API_BASE_URL,
        header01:"Forgot your password?",
        emailId:"#email",
        resetButton:"Reset password",
        rememberPassword:"Remember password?",
        resetmessage01:"Set a new password",
        resetURL: RESET_INITIATE_API_PATH,
        resetmessage02:"Reset link sent",
        resetmessage03:"Email does not exist",
        reseterror:"Unable to reset password",
        statuscode: 200,
        statuscodefail: 400,
        emailtest: "test@example.com",
        firstDropdownText: "a, button:contains('Back'), button:contains('Login')",
    },
    dashboardtransaction: {
        message01: "body",
        message02: "be.visible",
        message03: "transactions",
        message04: "[OK] Found Transactions heading",
        message05: "[OK] Found transaction-related content",
        message06: "[NO] Transactions text not found",
        message07: "input",
        message08: "[NO] No inputs found",
        message09: "placeholder",
        message10: "type",
        message11: "search",
        message12: "test",
        message13: "[OK] Typed in search input",
        message14: "[NO] Search input not found",
        message15: "transaction",
        message16: "transaction type",
        message17: "status",
        message18: "date",
        message19: "[OK] Found filter controls",
        message20: "[NO] Filter controls not found",
        message21: "include",
        waitcode: 2000,
    },

    dashboard: {
        message01: "body",
        message02: "be.visible",
        message03: "✅ Dashboard home page loaded",
        message04: "dashboard",
        message05: "groceries",
        message06: "orders",
        message07: "donations",
        message08: "transactions",
        message09: "✅ Found navigation elements",
        message10: "❌ No navigation elements found",
        message11: "button, a, input",
        message12: "❌ No interactive elements found",
        message13: "total",
        message14: "recent",
        message15: "overview",
        message16: "✅ Found dashboard content",
        message17: "❌ No dashboard content found",
        message18: "div, section, article, main",
        message19: "❌ No container elements found",
        message20: "button",
        waitcode01: 2000,
        message21: "✅ Button clicked",
        message22: "❌ No buttons to click",
        message23: "❌ No links found",
        message24: "/login",
        message25: "✅ Redirected to login (authentication required)",
        message26: "✅ Dashboard home page loaded successfully",
        message27: "a",
        message28: "✅ Found ${$elements.length} interactive elements",
        message29: "Element ${index}: <${tagName}> '${text}'",
        message30: "✅ Found ${$containers.length} container elements that might contain dashboard widgets",
        message31: "✅ Clicking first button: '${buttonText}'",
        message32: "✅ Found ${$links.length} links",
        message33: "Link ${index}: '${text}' -> ${href}",
        message34: "⚠️ Unexpected URL: ${url}",
    },

    dashboardprofile: {
        pageUrl01: "/dashboard/profile",
        waitcode: 2000,
        message01: "include",
        message02: "body",
        message03: "be.visible",
        message04: "contact information",
        message05: "✅ Found Contact Information section",
        message06: "❌ Contact Information section not found",
        message07: "security",
        message08: "✅ Found Security section",
        message09: "❌ Security section not found",
        message10: "Update address",
        message11: "change address",
        message12: "✅ Change Address page opened",
        message13: "delivery address",
        message14: "✅ Address form visible",
        message15: "❌ Address form not detected",
        message16: "Update password",
        message17: "✅ Update password page opened",
        message18: "❌ Update password page not detected",
        message19: "input",
        message20: "OldPass123!",
        message21: "NewPass123!",
        message22: "✅ Typed into password fields",
        message23: "❌ Password inputs not found",
        message24: "button",
        message25: "✅ Clicked Update password button",
        message26: "Enable two-factor authentication",
        message27: "two-factor authentication",
        message28: "✅ Two-factor authentication page opened",
        message29: "authenticator",
        message30: "✅ Authenticator instructions visible",
        message31: "❌ Two-factor page not detected",
        message32: "legal",
        message33: "✅ Found Legal section",
        message34: "❌ Legal section not found",
        message35: "privacy policy",
        message36: "✅ Found Privacy policy link",
        message37: "terms of service",
        message38: "✅ Found Terms of service link",
        message39: "cookies",
        message40: "✅ Found Cookies link",
        waitcode02: 800,
        message41: "open",
        message42: "windowOpen",
        message43: "Privacy policy",
        message44: "@windowOpen",
        message45: "have.been.called",
        message46: "❌ Privacy policy URL not found",
        message47: /terms of service/i,
        message48: "Terms of Service",
        message49: "❌ Terms of Service URL not found",
        message50: "Cookie Notice",
        message51: "❌ Cookies URL not found",
        message52: "/dashboard/profile",
        message53: "update password",
        message54: "Cookies",
    },
    dashboardorders: {
        pageUrl01: "/dashboard/orders",
        waitcode01: 2000,
        message01: "body",
        message02: "be.visible",
        message03: "✅ Dashboard orders page loaded",
        message04: "/login",
        message05: "✅ Orders page correctly redirects to login (authentication required)",
        message06: "/orders",
        message07: "✅ Orders page loaded successfully",
        message08: "order",
        message09: "purchase",
        message10: "invoice",
        message11: "transaction",
        message12: "Page content: ${bodyText}",
        message13: "✅ Page contains order-related content",
        message14: "❌ No order-related content found",
        message15: "⚠️ Unexpected URL: ${url}",
        message16: "button, a, input",
        message17: "✅ Found ${$elements.length} interactive elements",
        message18: "Element ${index}: <${tagName}> '${text}'",
        message19: "❌ No interactive elements found",
        message20: "button, a",
        message21: "✅ Clicking first ${tagName}: '${text}'",
        message22: "✅ Element clicked",
        message23: "❌ No clickable elements found",
    }
}

export const MakeCards = {
    login: {
        pageUrl: `${WEB_BASE_URL}${LOGIN_PATH}`,
        base: API_BASE_URL,
        path: LOGIN_PATH,
        phoneClassName: "PhoneInputInput",
        message01: "Welcome back",
        message01: "Login page should be accessible",
        button: "Login",
        buttonSelector: "a,button",
        message02: "Login form should be visible",
        formSelector: "form",
        inputSelector: "input:visible",
        message03: "Login form should have visible input fields",
        message04: "Login should have visible submit button",
        submitSelector: "button",
        message05: "Login input should accept typing",
        testInput: "08012345678",
        message06: "Login input should not be empty and contain digits",
        message07: "Login should not navigate away on empty submit",
        buttonRegex: /continue|login|sign in|next/i,
        buttonClickOptions: { force: true },
        urlInclude: "login",
        message08: "Create card button should be visible and clickable",
        createCardButtonSelector: "a:visible,button:visible",
        createCardButtonRegex: /create card/i,
        createCardButtonClickOptions: { force: true },
        createCardUrlRegex: /(create|card|onboard|register|verify|otp)/i,
        createCardMessage: "Create card flow should open on click",
        createCardUrlTimeout: 20000,
        loginUrlTimeout: 20000,
        loginButtonTimeout: 20000,
        loginFormTimeout: 20000,
        loginInputTimeout: 20000,
        loginSubmitButtonTimeout: 20000,
        createCardButtonTimeout: 20000,
  }
}

export const Pasca = {
    login: {
        pageUrl: `${WEB_BASE_URL}${LOGIN_PATH}`,
        base: API_BASE_URL,
        path: LOGIN_PATH,
        emailId: "input[type='email'], input[name='email'], input[placeholder*='email']",
        passwordId: "input[type='password'], input[name='password'], input[placeholder*='password']",
        button: "button[type='submit'], button:contains('Sign In'), button:contains('Login'), button:contains('Continue')",
        message01: "BackLogin",
        emailentry: "test@example.com",
        passwordentry: "Password123",
        message02:"Forgot password?",
        message03:"Continue with google",
        message04:"Invalid credentials",
        wrongemail:"wrong@example.com",
        wrongpassword:"wrongpassword",
        statuscode: 200,
        statuscodefail: 400,
        testemail:"test@example.com",
        testname:"Test User",
        testbalance:0,
        testphone:"0000000000",
        photo:"",
        temp_token:"temp-2fa-token",
        loginUrl:"/login",
        login2faUrl:"/login/2fa",
        loginmessage01:"OTP",
        loginmessage02:"OTP sent to your email",
        loginemail:"test@example.com",
        loginpassword:"Password123",
        loginmessage03:"Invalid OTP",
        instructionmessage01:"Enter 6-digit code on your Authenticator App",
        forgotPasswordArray: ["forgot", "reset"]
    },
    signUp: {
        pageUrl: `${WEB_BASE_URL}${SIGNUP_PATH}`,
        base: API_BASE_URL,
        header01: "Let's start by creating a free account",
        header02: "Enter your business details",
        nameId: "input[name='fullname'], input[placeholder*='name'], input[name='businessName']",
        emailId: "input[name='email'], input[placeholder*='email'], input[type='email']",
        passwordId: "input[name='password'], input[placeholder*='password'], input[type='password']",
        confirmPassword: "input[name='confirmPassword'], input[placeholder*='confirm'], input[type='password']",
        button: "button:contains('Continue'), button:contains('Create'), button:contains('Sign up')",
        checkboxId: "input[type='checkbox']",
        message01: "Account created successfully",
        message02: "Passwords do not match",
        statuscode: 200,
        statuscodefail: 400,
        inputId: "input[type='text'], input[type='email'], input[type='password']",
        firstDropdownText: "Business Name",
        message03: "Test Business",
        message04: "test@example.com",
        signUpArray: ["Let's start", "creating", "account", "Business"],
        checkForLogin: "a:contains('Log in'), a:contains('Already have an account')",
    },
    createPassword: {
        pageUrl: `${WEB_BASE_URL}${CREATE_PASSWORD_PATH}`,
        base: API_BASE_URL,
        header01: "Create Password",
        header02: "Enter your new password",
        passwordId: "input[type='password'], input[name='password'], input[placeholder*='password']",
        confirmPassword: "input[type='password'], input[name='confirmPassword'], input[placeholder*='confirm']",
        button: "button[type='submit'], button:contains('Create'), button:contains('Continue'), button:contains('Save')",
        message01: "Create password page loaded successfully",
        message02: "Passwords do not match",
        message03: "Submit button found",
        statuscode: 200,
        statuscodefail: 400,
        waitcode: 3000,
        message04: "Successfully typed in password field",
        message05: "Password form submitted successfully",
        firstDropdownText: "TestPassword123",
        secondDropdownText: "DifferentPassword456",
        thirdDropdownText: "button[type='submit'], button:contains('Continue')",
        createPasswordArray: ["Create", "Password"],
    },
    resetPassword: {
        pageUrl: `${WEB_BASE_URL}/create-password`,
        base: API_BASE_URL,
        header01: "Reset Password", 
        header02: "Enter your new password",
        passwordId: "input[type='password'], input[name='password'], input[placeholder*='password']",
        confirmPassword: "input[type='password'], input[name='confirmPassword'], input[placeholder*='confirm']",
        button: "button[type='submit'], button:contains('Reset'), button:contains('Continue'), button:contains('Save')",
        message01: "Password reset successfully",
        message02: "Passwords do not match",
        statuscode: 200,
        statuscodefail: 400,
        firstDropdownText: "TestPassword123",
        secondDropdownText: "DifferentPassword456",
        resetPasswordArray: ["Password", "Reset", "New"],
    },
    forgotPassword: {
        pageUrl: `${WEB_BASE_URL}${FORGOT_PASSWORD_PATH}`,
        path: FORGOT_PASSWORD_PATH,
        base: API_BASE_URL,
        header01: "Forgot your password?",
        emailId: "input[type='email'], input[name='email'], input[placeholder*='email']",
        resetButton: "button[type='submit'], button:contains('Reset'), button:contains('Send')",
        rememberPassword: "a:contains('Remember'), a:contains('Back'), a:contains('Login')",
        message01: "Set a new password",
        resetURL: RESET_INITIATE_API_PATH,
        message02: "Reset link sent",
        message03: "Email does not exist",
        reseterror: "Unable to reset password",
        statuscode: 200,
        statuscodefail: 400,
        emailtest: "test@example.com",
        message04: "Reset",
        firstDropdownText: "a, button:contains('Back'), button:contains('Login')",
    }
}

export const Taxporta = {
    login: {
        pageUrl: `${WEB_BASE_URL}${LOGIN_PATH}`,
        base: API_BASE_URL,
        path: LOGIN_PATH,
        message01: "exist",
        message02: /email address/i,
        message03: /password/i,
        message04: /continue/i,
        message05: /login with payer id/i,
        message06: /forgot password/i,
        message07: /create account/i,
        message08: /account login/i,
        message09: "Forgot password link found",
        message10: "Login page loaded successfully",
        message11: "Successfully typed in login form fields",
        message12: "Login page text links found",
        message13: "Switched to Payer ID login",
        message14: "Typed Payer ID",
        message15: "Login button found",
        message16: "Still on login page - may need additional steps",
        message17: "Successfully logged in with Payer ID",
        message18: "1234567890",
        message19: "be visible",
        message20: "/login",
        waitcode01: 3000,
        dropdownText01: "Forgot password",
        dropdownText02: "Account Login",
        dropdownText03: "Login with Payer ID",
        dropdownText04: "Create account",
        dropdownText05: "user@example.com",
        dropdownText06: "Password123",
        dropdownText07: "TEST_EMAIL",
        dropdownText08: "TEST_PASSWORD",
        dropdownText09: "FORGOT_PASSWORD_TEXT",
        dropdownText10: "ACCOUNT_LOGIN_HEADING",
        dropdownText11: "PAYER_ID_TEXT",
        dropdownText12: " CREATE_ACCOUNT_TEXT",
        text: "input[type='text'], input[name='payerId'], input[placeholder*='payer'], input[placeholder*='ID']",
        button: "button[type='submit'], button:contains('Continue'), button:contains('Submit'), button:contains('Login')",

    },

    forgotpassword: {
        pageUrl: `${WEB_BASE_URL}${FORGOT_PASSWORD_PATH}`,
        base: API_BASE_URL,
        path: FORGOT_PASSWORD_PATH,
        waitcode01: 3000,
        waitcode02: 5000,
        waitcode03: 2000,
        message01: "Forgot Password",
        message02: "exist",
        message03: "/forgot-password",
        message04: "Forgot password page opened",
        message05: "Email input field found",
        message06: "Continue button found",
        email: "input[type='email'], input[name='email'], input[placeholder*='email']",
        message07: "Continue",
        message08: "be visible",
        message09: "Typed email address",
        message10: "body",
        message11: "button",
        message12: "Successfully navigated away from forgot password page",
        message13: "Typed in",
        message14: "test@example.com",
        message15: "Still on forgot password page - checking for success message",
    },
    loginpayer:{
        pageUrl: `${WEB_BASE_URL}${LOGIN_PATH}`,
        base: API_BASE_URL,
        path: LOGIN_PATH,
        message01: "be.visible",
        message02: "/login",
        message03: "Payer ID login link clicked",
        inputtext: "input[type='text'], input[name='payerId'], input[placeholder*='payer'], input[placeholder*='ID']",
        message04: "be.visible",
        dropdownText01: "Login with Payer ID",
        number: "1234567890",
        message05: "Typed Payer ID successfully",
        message06: "Typed Payer",
        inputbutton: "button[type='submit'], button:contains('Continue'), button:contains('Submit'), button:contains('Login')",
        waitcode: 3000,
        message07: "body",
        message08: "Successfully moved to next step or logged in",
        message09: "Submit button found",
        message10: "Still on login page - checking for changes",
    }
}
