// Base URL for your frontend app pages visited by Cypress (e.g. /login, /sign-up).

// Create a variable called WEB_BASE_URL
const WEB_BASE_URL =

// Check if Cypress exists and if a baseUrl has been set in Cypress config
    typeof Cypress !== "undefined" && Cypress.config("baseUrl")

     // If true, use the baseUrl from Cypress config
        ? Cypress.config("baseUrl")

    // Otherwise, use localhost:3000 as the default frontend URL
        : "http://localhost:3000";

// Base URL for your backend API used by app requests (staging by default fallback).
const API_BASE_URL =  "https://staging-api.sendsile.com/api/v1"

// Route path for login page and login API intercept pattern.
const LOGIN_PATH = "/login"
// Route path for sign-up page.
const SIGNUP_PATH = "/sign-up"
// Route path for create-password page.
const CREATE_PASSWORD_PATH = "/create-password"
// Route path for forgot-password page.
const FORGOT_PASSWORD_PATH = "/forgot-password"
// Route path for email verification instruction page.
const EMAIL_VERIFICATION_PATH = "/email-verification"
// Route path template for email verification link with params.
const EMAIL_VERIFICATION_TOKEN_PATH = "/email-verification/:token/:id"
// API path used for register endpoint intercepts.
const REGISTER_API_PATH = "/register"
// API path used for forgot-password reset-initiate intercepts.
const RESET_INITIATE_API_PATH = "/password/reset/initiate"
// API path used for resend verification email intercepts.
const RESEND_EMAIL_API_PATH = "/email/resend"

export const Sendsile = {
    login: {
        pageUrl: `${WEB_BASE_URL}${LOGIN_PATH}`,
        base: API_BASE_URL,
        path: LOGIN_PATH,
        emailId: "#email",
        message01: "Login to your account",
        emailentry: "hello@test.com",
        passwordentry: "mypassword",
        message02:"Forgot password?",
        message03:"Continue with google",
        message04:"Invalid credentials",
        wrongemail:"wrong@example.com",
        wrongpassword:"wrongpassword",
        button:"Continue",
        statuscode: 200,
        statuscodefail: 400,
        testemail:"user@example.com",
        testname:"Test User",
        testbalance:0,
        testphone:"0000000000",
        photo:"",
        temp_token:"temp-2fa-token",
        loginUrl:"/login",
        login2faUrl:"/login/2fa",
        loginmessage01:"OTP",
        loginmessage02:"OTP sent to your email",
        loginemail:"user@example.com",
        loginpassword:"Password123",
        loginmessage03:"Invalid OTP",
        instructionmessage01:"Enter 6-digit code on your Authenticator App",
    },
    signup: {
        pageUrl: `${WEB_BASE_URL}${SIGNUP_PATH}`,
        base: API_BASE_URL,
        message01: "Let's sign you up first",
        nameId: "#fullname",
        emailId: "#email",
        passwordId: "#password",
        confirmPassword: "confirmPassword",
        button: "Continue",
        statuscode: 200,
        responsemail: "user@example.com",
        message02: "Passwords do not match",
        registerURL: REGISTER_API_PATH,
        message03: "Successfully filled vailable form fields",
        statuscodefail: 400,
        waitcode: 3000,
        message04: "Login link found",
        emailURL: EMAIL_VERIFICATION_PATH,
    },
    emailVerification: {
        pageUrl: `${WEB_BASE_URL}${EMAIL_VERIFICATION_PATH}`,
        verifyUrl: `${WEB_BASE_URL}/email-verification/test-token/123?signature=abc&expires=1`,
        base: API_BASE_URL,
        header01: "Check your inbox",
        header02: "A verification email has been sent to your email",
        resendButton: "Resend verification email",
        resendmessage01: "Verification email resent",
        resenderror: "Unable to resend verification email",
        resendUrl:"/email/verify/test-token/123?signature=abc&expires=1",
        resendmessage02:"Email verified",
        resendendpoint: RESEND_EMAIL_API_PATH,
        verifyendpoint: "/email/verify/test-token/123?*",
        statuscode: 200,
        statuscodefail: 400,

    },
    forgotpassword:{
        pageUrl: `${WEB_BASE_URL}${FORGOT_PASSWORD_PATH}`,
        base: API_BASE_URL,
        header01:"Forgot your password?",
        emailId:"#email",
        resetButton:"Reset password",
        rememberPassword:"Remember password?",
        resetmessage01:"Set a new password",
        resetURL: RESET_INITIATE_API_PATH,
        resetmessage02:"Reset link sent",
        resetmessage03:"Email does not exist",
        reseterror:"Unable to reset password",
        statuscode: 200,
        statuscodefail: 400,
        emailtest: "test@example.com",
        firstDropdownText: "a, button:contains('Back'), button:contains('Login')",
    },
    dashboardtransaction: {
        message01: "body",
        message02: "be.visible",
        message03: "transactions",
        message04: "[OK] Found Transactions heading",
        message05: "[OK] Found transaction-related content",
        message06: "[NO] Transactions text not found",
        message07: "input",
        message08: "[NO] No inputs found",
        message09: "placeholder",
        message10: "type",
        message11: "search",
        message12: "test",
        message13: "[OK] Typed in search input",
        message14: "[NO] Search input not found",
        message15: "transaction",
        message16: "transaction type",
        message17: "status",
        message18: "date",
        message19: "[OK] Found filter controls",
        message20: "[NO] Filter controls not found",
        message21: "include",
        waitcode: 2000,
    },

    dashboard: {
        pageUrl: 'https://www.sendsile.com/dashboard',
    message: 'API request processed',
    message01: 'should load dashboard home page and show key UI sections',
    message02: 'should exercise dashboard interactive elements and verify navigation',
    message03: 'should validate password form errors and password update API responses',
    message04: 'should submit the address form and show both error and success states',
    message05: 'should handle two-factor authentication initiation and verification',
    root: '#root',
    transactionsPath: '/dashboard/transactions',
    billPaymentPath: '/dashboard/bill-payment',
    donationsPath: '/dashboard/donations',
    profilePath: '/dashboard/profile',
    testAccessToken: 'test-access-token',
    authToken: 'Bearer test-access-token',
    walletAmount: '5000',
    otpCode: '123456',
    wrongPassword: 'short',
    currentPassword: 'CurrentPass1',
    newPassword: 'NewPassword1',
    mismatchedPassword: 'NewPassword2',
    streetAddress: '14 Bourdillon Road',
    region: 'Lagos',
    city: 'Ikoyi',
    country: 'Nigeria',
    incorrectPasswordMessage: 'Current password is incorrect',
    passwordUpdateSuccessMessage: 'Password updated successfully',
    addressUpdateErrorMessage: 'Unable to update address',
    addressUpdateSuccessMessage: 'Address updated successfully',
    twoFactorSuccessMessage: '2FA enabled successfully',
    twoFactorSecret: 'ABC123SECRET',
    notificationEmptyMessage: 'You have no notifications',
    billPaymentPlaceholder: 'Coming soon',
    headings: {
      walletBalance: 'Wallet balance',
      quickAccess: 'Quick access',
      recentTransactions: 'Recent transactions',
      contactInformation: 'Contact Information',
      updatePassword: 'Update password',
      changeAddress: 'CHANGE ADDRESS',
      twoFactorAuthentication: 'TWO-FACTOR AUTHENTICATION',
      fundWallet: 'Fund your',
      paymentMode: 'Select mode of',
      notifications: 'Notifications',
    },
    buttons: {
      fundWallet: 'Fund wallet',
      seeAll: 'See all',
      logout: 'Logout',
      updatePassword: 'Update password',
      updateAddress: 'Update Address',
      makePayment: 'Make payment',
    },
    links: {
      home: 'Home',
      orders: 'Orders',
      groceries: 'Groceries',
      billPayment: 'Bill payment',
      donations: 'Donations',
      transactions: 'Transactions',
      profile: 'Profile',
    },
    quickAccessCards: {
      groceries: 'Buy groceries',
      payBills: 'Pay bills',
      donations: 'Make a donation',
    },
    selectors: {
      table: 'table',
      tableDateHeader: 'Date',
      transactionNarration: 'Fresh produce order',
      notificationToggle: 'div.shadow-\\\\[0px_3px_4px_0px\\\\]',
      walletAmountInput: 'input[name="amount"]',
      modalCloseButton: 'button.absolute.top-4.right-4',
      oldPasswordInput: '#oldPassword',
      newPasswordInput: '#new-password',
      confirmPasswordInput: '#confirm-password',
      streetAddressInput: '#street_address',
      regionInput: '#region',
      cityInput: '#city',
      countryInput: '#country',
      twoFactorSwitch: '#switch',
      qrCodeImage: 'img[alt="qr_code"]',
      otpInputs: 'form input',
    },
    paymentProvider: 'Paystack',
    transactions: [
      {
        transaction_id: 'txn-001',
        date: '2026-04-08',
        amount: 'NGN 25,000',
        type: 'Groceries',
        narration: 'Fresh produce order',
        status: 'successful',
      },
      {
        transaction_id: 'txn-002',
        date: '2026-04-07',
        amount: 'NGN 10,500',
        type: 'Donation',
        narration: 'Community support',
        status: 'pending',
      },
    ],
    categories: [
      {
        id: 'cat-001',
        name: 'Foodstuff',
      },
    ],
    userData: {
      id: 'user-123',
      name: 'Test User',
      email: 'test@example.com',
      phone: '08012345678',
      balance: 250000,
      delivery_address: '12 Admiralty Way, Lekki',
      two_factor_enabled: 'disabled',
      pin_set: true,
    },
    persistedLocation: {
      state: {
        isOpen: false,
        location: 'nigeria',
      },
      version: 0,
    },
    twoFactorPayload: {
      secret: 'ABC123SECRET',
      qr_code_image:
        '<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" width="120" height="120"><rect width="120" height="120" fill="white"/><rect x="20" y="20" width="20" height="20" fill="black"/><rect x="50" y="20" width="20" height="20" fill="black"/><rect x="80" y="20" width="20" height="20" fill="black"/></svg>',
    },
        
    },

    dashboardprofile: {
        pageUrl01: "/dashboard/profile",
        waitcode: 2000,
        message01: "include",
        message02: "body",
        message03: "be.visible",
        message04: "contact information",
        message05: "✅ Found Contact Information section",
        message06: "❌ Contact Information section not found",
        message07: "security",
        message08: "✅ Found Security section",
        message09: "❌ Security section not found",
        message10: "Update address",
        message11: "change address",
        message12: "✅ Change Address page opened",
        message13: "delivery address",
        message14: "✅ Address form visible",
        message15: "❌ Address form not detected",
        message16: "Update password",
        message17: "✅ Update password page opened",
        message18: "❌ Update password page not detected",
        message19: "input",
        message20: "OldPass123!",
        message21: "NewPass123!",
        message22: "✅ Typed into password fields",
        message23: "❌ Password inputs not found",
        message24: "button",
        message25: "✅ Clicked Update password button",
        message26: "Enable two-factor authentication",
        message27: "two-factor authentication",
        message28: "✅ Two-factor authentication page opened",
        message29: "authenticator",
        message30: "✅ Authenticator instructions visible",
        message31: "❌ Two-factor page not detected",
        message32: "legal",
        message33: "✅ Found Legal section",
        message34: "❌ Legal section not found",
        message35: "privacy policy",
        message36: "✅ Found Privacy policy link",
        message37: "terms of service",
        message38: "✅ Found Terms of service link",
        message39: "cookies",
        message40: "✅ Found Cookies link",
        waitcode02: 800,
        message41: "open",
        message42: "windowOpen",
        message43: "Privacy policy",
        message44: "@windowOpen",
        message45: "have.been.called",
        message46: "❌ Privacy policy URL not found",
        message47: /terms of service/i,
        message48: "Terms of Service",
        message49: "❌ Terms of Service URL not found",
        message50: "Cookie Notice",
        message51: "❌ Cookies URL not found",
        message52: "/dashboard/profile",
        message53: "update password",
        message54: "Cookies",
    },
    dashboardorders: {
        pageUrl01: "/dashboard/orders",
        waitcode01: 2000,
        message01: "body",
        message02: "be.visible",
        message03: "✅ Dashboard orders page loaded",
        message04: "/login",
        message05: "✅ Orders page correctly redirects to login (authentication required)",
        message06: "/orders",
        message07: "✅ Orders page loaded successfully",
        message08: "order",
        message09: "purchase",
        message10: "invoice",
        message11: "transaction",
        message12: "Page content: ${bodyText}",
        message13: "✅ Page contains order-related content",
        message14: "❌ No order-related content found",
        message15: "⚠️ Unexpected URL: ${url}",
        message16: "button, a, input",
        message17: "✅ Found ${$elements.length} interactive elements",
        message18: "Element ${index}: <${tagName}> '${text}'",
        message19: "❌ No interactive elements found",
        message20: "button, a",
        message21: "✅ Clicking first ${tagName}: '${text}'",
        message22: "✅ Element clicked",
        message23: "❌ No clickable elements found",
    },

    checkout: {
    pageUrl: 'https://www.sendsile.com/checkout',
    base: 'https://www.sendsile.com',
    message01: 'should display checkout page header',
    message02: 'should display order summary section',
    message03: 'should display shipping information form',
    message04: 'should display billing information form',
    message05: 'should display payment method selection',
    message06: 'should display order items list',
    message07: 'should handle coupon code functionality',
    message08: 'should display order total calculation',
    message09: 'should handle form validation',
    message10: 'should handle loading states',
    message11: 'should handle error states',
    message12: 'should be responsive on different viewports',
    message13: 'should complete checkout process successfully',
    message14: 'should handle valid inputs correctly',
    message15: 'should handle invalid inputs appropriately',
    message16: 'should handle all input field interactions',
    message17: 'should click buttons, type inputs, and navigate pages correctly',
    message18: 'should submit form successfully with valid data',
    message19: 'should handle send as a gift option with valid and invalid inputs',
    message20: 'should validate email input with various formats',
    message21: 'should validate name input fields',
    message22: 'should validate address input fields',
    message23: 'should validate phone number input',
    message24: 'should validate payment card information',
    message25: 'should validate form before submission',
    message26: 'should simulate realistic user shopping behavior',

    // Page structure
    root: '#root, .checkout-container, .main-content',
    pageTitle: 'h1:contains("Checkout"), h2:contains("Payment"), .checkout-title',
    pageDescription: '.checkout-description, .order-summary',

    // Order summary
    orderSummary: '.order-summary, .checkout-summary, .summary-section',
    orderItems: '.order-item, .product-item, .checkout-item',
    itemQuantity: '.quantity, .item-quantity, .qty',
    itemPrice: '.price, .item-price, .amount',
    subtotal: '.subtotal, .order-subtotal',

    // Shipping information
    shippingForm: '.shipping-form, .address-form',
    firstName: 'input[name*="firstName"], input[placeholder*="first"]',
    lastName: 'input[name*="lastName"], input[placeholder*="last"]',
    email: 'input[name*="email"], input[type="email"]',
    phone: 'input[name*="phone"], input[type="tel"]',
    address: 'input[name*="address"], textarea[name="address"]',
    city: 'input[name*="city"], input[placeholder*="city"]',
    state: 'select[name*="state"], .state-select',
    zipCode: 'input[name*="zip"], input[name*="postal"], input[placeholder*="zip"]',
    country: 'select[name*="country"], .country-select',

    // Billing information
    billingForm: '.billing-form, .payment-form',
    cardNumber: 'input[name*="cardNumber"], input[placeholder*="card"]',
    cardName: 'input[name*="cardName"], input[placeholder*="name"]',
    expiryDate: 'input[name*="expiry"], input[placeholder*="expiry"]',
    cvv: 'input[name*="cvv"], input[placeholder*="cvv"]',

    // Payment methods
    paymentMethods: '.payment-methods, .payment-options',
    creditCardOption: 'input[value="credit"], .credit-card-option',
    paypalOption: 'input[value="paypal"], .paypal-option',
    applePayOption: 'input[value="apple"], .apple-pay-option',
    googlePayOption: 'input[value="google"], .google-pay-option',

    // Coupon functionality
    couponInput: '.coupon-input, input[name*="coupon"]',
    couponButton: '.apply-coupon, button:contains("Apply")',
    couponMessage: '.coupon-message, .discount-message',

    // Order total
    orderTotal: '.order-total, .total-amount, .final-price',
    tax: '.tax, .tax-amount',
    shipping: '.shipping-cost, .delivery-fee',
    discount: '.discount, .coupon-discount',

    // Action buttons
    placeOrderBtn:
      '.place-order, button:contains("Place Order"), button:contains("Complete Purchase")',
    continueBtn: '.continue-shopping, button:contains("Continue Shopping")',
    backBtn: '.back-to-cart, button:contains("Back to Cart")',

    // Form validation
    requiredFieldError: '.error, .validation-error, .required',
    invalidEmailError: '.email-error, .invalid-email',
    invalidCardError: '.card-error, .invalid-card',

    // Loading and error states
    loadingIndicator: '.loading, .spinner, .loader, .processing',
    errorMessage: '.error-message, .alert-error, .checkout-error',
    successMessage: '.success-message, .alert-success, .order-success',

    // Responsive design
    mobileView: 'iphone-x',
    tabletView: 'ipad-2',
  },

groceries: {
    pageUrl: "https://www.sendsile.com/dashboard/groceries",
    root: '#root',
    navMenu: 'nav, .navbar, .sidebar, .menu',
    dashLink: 'a[href*="dashboard"], a:contains("Dashboard"), a:contains("Home")',
    headings: 'h1:contains("Groceries"), h2:contains("Groceries"), .title:contains("Groceries")',
    description: 'p:contains("grocery"), .subtitle:contains("grocery")',
    categoryCard: '.category-card, .grocery-category, .section-card',
    categoryNav: '.category-nav, .tab-navigation, .filter-tabs',
    productGrid: '.product-grid, .product-list, .grocery-items',
    productCard: '.product-card, .grocery-item, .item-card',
    productNames: '.product-name, .item-name, .grocery-name',
    productPrices: '.price, .amount, :contains("$")',
    productImages: 'img[alt*="product"], .product-image, .item-image',
    searchInput: 'input[type="search"], input[placeholder*="search"], .search-box',
    searchFunc: 'input[type="search"], input[placeholder*="search"]',
    filterDropdown: 'select, .dropdown, .filter',
    sortingOption: '.sort-control, .sort-dropdown, :contains("Sort")',
    cartButton: 'button:contains("Add to Cart"), .add-to-cart, .cart-btn',
    cartIcon: '.cart-icon, .shopping-cart, :contains("Cart")',
    cartItem: '.cart-count, .badge, :contains("0")',
    offerBanners: '.offer-banner, .discount-banner, .promo-section',
    discountBadges: '.discount-badge, .sale-tag, :contains("%")',
    loadingIndicator: '.loading, .spinner, .loader, .skeleton',
    emptyState: '.empty-state, .no-data, :contains("No products"), :contains("Empty")',
    errorMessage: '.error, .alert-error, .error-message, [role="alert"]',
    retryButton: 'button:contains("Retry"), button:contains("Try again"), .retry-btn',
    testLink: 'a[href]',
    message: 'Groceries page loaded successfully',
    message01: 'should display correct page title and basic structure',
    message02: 'should display dashboard navigation elements',
    message03: 'should display groceries page header',
    message04: 'should display grocery categories or sections',
    message05: 'should display grocery products',
    message06: 'should display product information',
    message07: 'should display search and filter controls',
    message08: 'should display shopping cart functionality',
    message09: 'should display special offers or discounts',
    message10: 'should handle loading and empty states appropriately',
    message11: 'should be responsive on different viewports',
    message12: 'should handle basic user interactions',
    message13: 'should handle error states gracefully',
    message14: 'should display product details correctly',
    message15: 'should handle adding/removing items from cart',
    message16: 'should filter and sort products correctly',
    message17: 'should validate search input functionality',
    message18: 'should ensure buttons are enabled/disabled appropriately',
    message19: 'should display dynamic UI updates after user actions',
    message20: 'should intercept and validate API requests',
    message21: 'should validate success scenarios',
    message22: 'should validate failure scenarios',
    message23: 'should verify cart state updates',
    productDetailsModal: '.product-details-modal, .product-detail-page, .modal-product-details',
    productDescription: '.product-description, .item-description, .description-text',
    clearSearchButton: '.clear-search-button, .search-clear-btn, button[aria-label="Clear search"]',
    mobileView: 'iphone-x',
    tabletView: 'ipad-2',
  },

quickView: {
    pageUrl:
      'https://www.sendsile.com/quick-view/e9142bbb-9bbc-47a6-a7db-5bfae66b583f?v=8b3fb20a-4090-401e-9bf0-d0099409c2ee',
    base: 'https://www.sendsile.com',
    message01: 'should display order details header',
    message02: 'should display order information section',
    message03: 'should display order items list',
    message04: 'should display order status section',
    message05: 'should display order timeline section',
    message06: 'should display shipping information',
    message07: 'should display billing information',
    message08: 'should display order total section',
    message09: 'should handle order actions',
    message10: 'should display order tracking information',
    message11: 'should handle loading states',
    message12: 'should handle error states',
    message13: 'should be responsive on different viewports',
    message14: 'should display order actions correctly',
    message15: 'should handle order tracking functionality',
    message16: 'should display detailed product information',
    message17: 'should handle navigation to related pages',

    // Page structure
    root: '#root, .order-container, .main-content',
    pageTitle: 'h1:contains("Order Details"), h2:contains("Order"), .order-title',
    pageDescription: '.order-description, .order-summary',

    // Order information
    orderInfo: '.order-info, .order-details, .order-section',
    orderId: ".order-id, .order-number, :contains('Order #')",
    orderDate: ".order-date, .order-date-info, :contains('Order Date')",
    orderStatus: '.order-status, .status-badge, .order-state',

    // Order items
    itemsList: '.order-items, .items-list, .product-list',
    orderItem: '.order-item, .product-item, .item-row',
    itemName: '.item-name, .product-name, .item-title',
    itemPrice: '.item-price, .product-price, .item-amount',
    itemQuantity: '.item-quantity, .product-quantity, .item-qty',
    itemImage: '.item-image, .product-image, .item-photo',

    // Order status
    statusSection: '.status-section, .order-status-section',
    statusBadge: '.status-badge, .order-status-badge',
    trackingNumber: ".tracking-number, .tracking-info, :contains('Tracking')",

    // Order timeline
    timeline: '.order-timeline, .activity-timeline, .order-history',
    timelineEvent: '.timeline-event, .activity-item, .order-activity',
    eventDate: '.event-date, .activity-date',
    eventDescription: '.event-description, .activity-description',

    // Shipping information
    shippingInfo: '.shipping-info, .delivery-info, .shipping-section',
    shippingAddress: '.shipping-address, .delivery-address, .order-address',
    recipientName: '.recipient-name, .customer-name, .shipping-name',
    shippingMethod: '.shipping-method, .delivery-method, .shipping-type',
    estimatedDelivery: '.estimated-delivery, .delivery-date, .shipping-estimate',

    // Billing information
    billingInfo: '.billing-info, .payment-info, .billing-section',
    billingAddress: '.billing-address, .payment-address',
    paymentMethod: '.payment-method, .payment-type, .order-payment',
    cardLast4: ".card-last4, .payment-card, :contains('****')",

    // Order total
    totalSection: '.order-total, .summary-total, .total-section',
    subtotal: '.subtotal, .order-subtotal',
    tax: '.tax, .order-tax, .tax-amount',
    shipping: '.shipping-cost, .delivery-fee, .order-shipping',
    discount: '.discount, .coupon-discount, .order-discount',
    grandTotal: '.grand-total, .order-total, .final-amount',

    // Order actions
    actionsSection: '.order-actions, .action-buttons, .order-buttons',
    trackOrderBtn: '.track-order, button:contains("Track"), button:contains("Track Order")',
    downloadInvoiceBtn:
      '.download-invoice, button:contains("Download"), button:contains("Invoice")',
    cancelOrderBtn: '.cancel-order, button:contains("Cancel"), button:contains("Cancel Order")',
    reorderBtn: '.reorder, button:contains("Reorder"), button:contains("Buy Again")',

    // Order tracking
    trackingInfo: '.tracking-details, .tracking-section',
    trackingLink: 'a[href*="tracking"], .tracking-link, :contains("Track Package")',

    // Form validation
    requiredFieldError: '.error, .validation-error, .required',
    invalidDataError: '.error-message, .alert-error, .order-error',

    // Loading and error states
    loadingIndicator: '.loading, .spinner, .loader, .processing',
    errorMessage: '.error-message, .alert-error, .order-error',
    successMessage: '.success-message, .alert-success, .order-success',

    // Responsive design
    mobileView: 'iphone-x',
    tabletView: 'ipad-2',
  },

}

export const MakeCards = {
    login: {
        pageUrl: `${WEB_BASE_URL}${LOGIN_PATH}`,
        base: API_BASE_URL,
        path: LOGIN_PATH,
        phoneClassName: "PhoneInputInput",
        message01: "Welcome back",
        message01: "Login page should be accessible",
        button: "Login",
        buttonSelector: "a,button",
        message02: "Login form should be visible",
        formSelector: "form",
        inputSelector: "input:visible",
        message03: "Login form should have visible input fields",
        message04: "Login should have visible submit button",
        submitSelector: "button",
        message05: "Login input should accept typing",
        testInput: "08012345678",
        message06: "Login input should not be empty and contain digits",
        message07: "Login should not navigate away on empty submit",
        buttonRegex: /continue|login|sign in|next/i,
        buttonClickOptions: { force: true },
        urlInclude: "login",
        message08: "Create card button should be visible and clickable",
        createCardButtonSelector: "a:visible,button:visible",
        createCardButtonRegex: /create card/i,
        createCardButtonClickOptions: { force: true },
        createCardUrlRegex: /(create|card|onboard|register|verify|otp)/i,
        createCardMessage: "Create card flow should open on click",
        createCardUrlTimeout: 20000,
        loginUrlTimeout: 20000,
        loginButtonTimeout: 20000,
        loginFormTimeout: 20000,
        loginInputTimeout: 20000,
        loginSubmitButtonTimeout: 20000,
        createCardButtonTimeout: 20000,
  }
}

export const Pasca = {
    login: {
        pageUrl: `${WEB_BASE_URL}${LOGIN_PATH}`,
        base: API_BASE_URL,
        path: LOGIN_PATH,
        initialWaitTime: 3000,
        bodySelector: "body",
        beVisibleAssertion: "be.visible",
        pageLoadedLog: "✅ Pasca login page loaded",
        brandingKeyword1: "Pasca",
        brandingKeyword2: "Sign in to your workspace",
        brandingFoundLog: "✅ Found Pasca login page content",
        brandingNotFoundLog: "❌ Pasca login content not found",
        emailId: "input[name='email']",
        emailInputFoundLog: "✅ Found email input",
        email: "test@example.com",
        emailTypedLog: "✅ Typed email",
        emailInputNotFoundLog: "❌ Email input not found",
        passwordId: "input[name='password']",
        passwordInputFoundLog: "✅ Found password input",
        newpassword: "Password123",
        passwordTypedLog: "✅ Typed password",
        passwordInputNotFoundLog: "❌ Password input not found",
        button: "button[type='submit']",
        loginButtonFoundLog: "✅ Login button found",
        linkSelector: "a",
        forgotPasswordLinkRegex: /forgot|reset/i,
        forgotPasswordLinkFoundLog: "✅ Forgot password link found",
        signUpLinkRegex: /sign up|create account|register/i,
        signUpLinkFoundLog: "✅ Sign up link found",
        taxProMaxKeyword1: "TaxPro Max",
        taxProMaxKeyword2: "Federal Inland Revenue Service",
        taxProMaxFoundLog: "✅ Found TaxPro Max login option",
        taxProMaxNotFoundLog: "⚠️ TaxPro Max option not found",
        urlLogTemplate: "Current URL after login attempt: ${url}",
        dashboardPath: "dashboard",
        workspacePath: "workspace",
        loginSuccessLog: "✅ Login successful - redirected to dashboard",
        loginPath: "login",
        loginPageErrorCheckLog: "⚠️ Still on login page - checking for errors",
        errorKeyword1: "error",
        errorKeyword2: "invalid",
        errorMessageDisplayedLog: "✅ Error message displayed",
        errorMessageNotFoundLog: "⚠️ No error message found",
        completionLogTemplate: "✅ Login attempt completed, URL: ${url}",
        wrongexample: "wrong@example.com",
        wrongpassword: "wrongpassword",
        errorKeyword3: "credentials",
        wrongCredentialsErrorLog: "✅ Error message displayed for wrong credentials",
        wrongCredentialsNoErrorLog: "⚠️ No error message for wrong credentials",
    },
    signUp: {
        pageUrl: `${WEB_BASE_URL}${SIGNUP_PATH}`,
        base: API_BASE_URL,
        pageTitle: "Let's start by creating a free account",
        formTitle: "Enter your business details",
        nameId: "input[name='fullname'], input[name*='business'], input[name*='company'], input[name='name'], input[id*='name'], input[id*='business'], input[placeholder*='name'], input[placeholder*='Name'], input[placeholder*='business'], input[placeholder*='Business']",
        emailId: "input[name='email'], input[placeholder*='email'], input[type='email']",
        passwordId: "input[name='password'], input[placeholder*='password'], input[type='password']",
        confirmPassword: "input[name='confirmPassword'], input[placeholder*='confirm'], input[type='password']",
        button: "button:contains('Continue'), button:contains('Create'), button:contains('Sign up')",
        checkboxId: "input[type='checkbox']",
        accountCreatedSuccessMessage: "Account created successfully",
        passwordMismatchErrorMessage: "Passwords do not match",
        statuscode: 200,
        statuscodefail: 400,
        inputId: "input[type='text'], input[type='email'], input[type='password']",
        testBusinessName: "Test Business",
        testEmail: "test@example.com",
        signUpArray: ["Let's start", "creating", "account", "Business"],
        loginLinkSelector: "a:contains('Log in'), a:contains('Already have an account')",
        businessTypeSelector: "select, [role='combobox'], .select, button[aria-haspopup='listbox']",
        businessTypeOption: "Limited Liability",
        userTypeTaxpayerRegex: /Taxpayer/i,
        termsKeyword: "Terms of Use",
        privacyKeyword: "Privacy Policy",
        brandingKeyword: "Pasca",
        createAccountKeyword: "creating a free account"
    },
    createPassword: {
        pageUrl: `${WEB_BASE_URL}${CREATE_PASSWORD_PATH}`,
        base: API_BASE_URL,
        pathFragment: "create-password",
        bodySelector: "body",
        beVisibleAssertion: "be.visible",
        pageLoadedLog: "✅ Pasca create password page loaded",
        headerFoundLog: "✅ Found Create Password header",
        titleRegex: /Create Password/i,
        timeout01:  15000,
        timeout02: 10000,
        assertionContain: "contain.text",
        keywordPassword:  "password",
        subheaderFoundLog: "✅ Found subheader instructions",
        passwordInputFoundLog: "✅ Found password input",
        passwordTypedLog: "✅ Typed password",
        passwordInputNotFoundLog: "❌ Password input not found",
        confirmPasswordInputFoundLog: "✅ Found confirm password input",
        confirmPasswordTypedLog: "✅ Typed confirm password",
        confirmPasswordInputNotFoundLog: "❌ Confirm password input not found",
        buttonFoundLog: "✅ Found create/continue button",
        passwordId: "input[name='password'], input[name*='password'], input[placeholder*='password'], input[type='password']",
        newpassword: "NewPassword123!",
        confirmPassword: "input[name='confirmPassword'], input[name*='confirm'], input[placeholder*='confirm'], input[type='password']:nth-of-type(2)",
        mismatchedPassword: "MismatchedPassword123!",
        button: "button[type='submit']",
        validationWaitTime: 2000,
        keywordMatch: "match",
        keywordSame: "same",
        keywordDifferent: "different",
        mismatchValidationDisplayedLog: "✅ Password mismatch validation displayed",
        mismatchValidationNotFoundLog: "⚠️ No password mismatch validation",
        matchingPasswordsTypedLog: "✅ Typed matching passwords",
        redirectWaitTime: 3000,
        loginRedirectPath: "login",
        loginRedirectSuccessLog: "✅ Redirected to login after password creation",
        dashboardRedirectPath: "dashboard",
        workspaceRedirectPath: "workspace",
        dashboardRedirectSuccessLog: "✅ Redirected to dashboard after password creation",
        createPasswordPath: "create-password",
        createPasswordErrorCheckLog: "⚠️ Still on create password page - checking for errors",
        errorKeyword1: "error",
        errorKeyword2: "requirements",
        errorKeyword3: "strength",
        requirementsErrorDisplayedLog: "✅ Password requirements error displayed",
        completionLogTemplate: "✅ Password creation completed, URL: ${url}",
        weakPasswordValue: "123",
        weakPasswordKeyword: "weak",
        strengthValidationDisplayedLog: "✅ Password strength validation displayed",
        strengthValidationNotFoundLog: "⚠️ No password strength validation",
        emptyFieldKeyword1: "required",
        emptyFieldKeyword2: "empty",
        emptyFieldsErrorLog: "✅ Validation error for empty password fields",
        emptyFieldsNoErrorLog: "⚠️ No validation for empty password fields",
        passwordInputsFoundLog: "✅ Found password inputs",
        visibilityToggleKeyword1: "eye",
        visibilityToggleKeyword2: "visibility",
        visibilityToggleFoundLog: "✅ Password visibility toggle found",
        visibilityToggleNotFoundLog: "⚠️ No password visibility toggle found",
        passwordLengthKeyword: "characters",
        visibilityToggleKeyword3: "show",
    },
    
    forgotPassword: {
        pageUrl: `${WEB_BASE_URL}${FORGOT_PASSWORD_PATH}`,
        path: FORGOT_PASSWORD_PATH,
        base: API_BASE_URL,
        bodySelector: "body",
        pageLoadTimeout: 15000,
        elementVisibilityTimeout: 10000,
        formSubmitWaitTime: 3000,
        validationWaitTime: 2000,
        email: "test@example.com",
        beVisibleAssertion: "be.visible",
        pageLoadedLog: "✅ Pasca forgot password page loaded",
        pageContentFoundLog: "✅ Found page content related to password recovery",
        emailInputFoundLog: "✅ Found email input",
        emailTypedLog: "✅ Typed email address",
        emailInputNotFoundLog: "❌ Email input not found",
        buttonSelector: "button",
        resetButtonFoundLog: "✅ Found reset button",
        backToLoginLinkFoundLog: "✅ Found back to login link",
        emailTypedForResetLog: "✅ Typed email for password reset",
        forgotPasswordPath: "forgot-password",
        sentKeyword: "sent",
        emailKeyword: "email",
        resetInstructionsSentLog: "✅ Reset instructions sent message displayed",
        errorKeyword1: "error",
        errorKeyword2: "not found",
        invalidEmailErrorLog: "✅ Error message for invalid email",
        loginPath: "login",
        checkEmailPath: "check-email",
        redirectAfterResetLog: "✅ Redirected after password reset request",
        completionLogTemplate: "✅ Password reset request completed, URL: ${url}",
        notFoundKeyword: "not found",
        invalidEmailErrorMessageDisplayedLog: "✅ Error message displayed for invalid email",
        invalidEmailErrorMessageNotFoundLog: "⚠️ No error message for invalid email",
        requiredKeyword: "required",
        emptyKeyword: "empty",
        emptyEmailValidationErrorLog: "✅ Validation error for empty email",
        emptyEmailValidationNotFoundLog: "⚠️ No validation for empty email",
        urlIncludeAssertion: "include",
        backToLoginPageSuccessLog: "✅ Successfully navigated back to login page",
        forgotPasswordPageErrorCheckLog: "⚠️ Still on forgot password page - checking for messages",
        titleRegex: /Forgot|Password|Reset|Recover/i,
        buttonRegex: /Reset|Send/i,
        backLinkRegex: /Login|Sign|Back|Remember/i,
        urlLogTemplate: "Current URL after password reset request: ${url}",
        emailId: "input[name='email']",
        button: "button[type='submit']",
        checkKeyword: "check",
        invalidKeyword: "invalid",
        invalidEmailTypedLog: "✅ Typed invalid email",
        validEmailKeyword: "valid email",
        invalidEmail:"invalid-email@example.com",
    },
    resetPassword: { // New section for reset password
        pageUrl: `${WEB_BASE_URL}${CREATE_PASSWORD_PATH}`, // Pasca uses same path for reset
        base: API_BASE_URL,
        pathFragment: "create-password",
        initialWaitTime: 3000,
        bodySelector: "body",
        beVisibleAssertion: "be.visible",
        pageLoadedLog: "✅ Pasca reset password page loaded",
        headerText: "Reset Password",
        headerFoundLog: "✅ Found 'Reset Password' header",
        subheaderText: "Enter your new password",
        subheaderFoundLog: "✅ Found 'Enter your new password' subheader",
        passwordInputSelector: "input[name='password']",
        passwordInputFoundLog: "✅ Found password input for reset",
        newPassword: "NewPassword123!",
        passwordTypedLog: "✅ Typed new password",
        passwordInputNotFoundLog: "❌ Password input not found",
        confirmPasswordInputSelector: "input[name='confirmPassword']",
        confirmPasswordInputFoundLog: "✅ Found confirm password input for reset",
        confirmPasswordTypedLog: "✅ Typed confirm new password",
        confirmPasswordInputNotFoundLog: "❌ Confirm password input not found",
        submitButtonSelector: "button[type='submit']",
        resetButtonFoundLog: "✅ Found reset button",
        mismatchedPassword: "MismatchedPassword123!",
        validationWaitTime: 2000,
        mismatchKeyword1: "match",
        mismatchKeyword2: "same",
        mismatchKeyword3: "different",
        mismatchValidationDisplayedLog: "✅ Password mismatch validation displayed for reset",
        mismatchValidationNotFoundLog: "⚠️ No password mismatch validation for reset",
        matchingPasswordsTypedLog: "✅ Typed matching new passwords for reset",
        redirectWaitTime: 3000,
        urlLogTemplate: "Current URL after password reset: ${url}",
        loginPath: "login",
        loginRedirectLog: "✅ Redirected to login after password reset",
        successPath1: "success",
        successPath2: "reset-success",
        successPageLoadedLog: "✅ Password reset success page loaded",
        createPasswordPath: "create-password",
        resetPageErrorCheckLog: "⚠️ Still on reset password page - checking for errors",
        errorKeyword1: "error",
        errorKeyword2: "requirements",
        errorKeyword3: "strength",
        requirementsErrorDisplayedLog: "✅ Password requirements error displayed",
        completionLogTemplate: "✅ Password reset completed, URL: ${url}",
        weakPasswordValue: "123",
        lengthKeyword1: "short",
        lengthKeyword2: "characters",
        lengthKeyword3: "minimum",
        lengthValidationDisplayedLog: "✅ Password length validation displayed",
        strengthIndicatorFoundLog: "✅ Password strength indicator found",
        strengthUIFoundLog: "✅ Password strength UI elements found",
        strengthIndicatorNotFoundLog: "⚠️ No password strength indicator found",
        requiredKeyword: "required",
        emptyKeyword: "empty",
        passwordKeyword: "password",
        emptyFormErrorLog: "✅ Validation error for empty reset form",
        emptyFormNoErrorLog: "⚠️ No validation for empty reset form",
        successKeyword1: "success",
        successKeyword2: "reset",
        successKeyword3: "updated",
        successKeyword4: "changed",
        successMessageDisplayedLog: "✅ Password reset success message displayed",
        successMessageNotFoundLog: "⚠️ No clear success message for password reset",
    }
}
export const Taxporta = {
    baseUrl: "https://taxporta.fctirs.gov.ng",
    login: {
        pageUrl: "https://taxporta.fctirs.gov.ng/login",
        brandingRegex: /Tax|FCT|IRS|Login/i,
        emailInput: "input[type='email'], input[name*='email']",
        passwordInput: "input[type='password'], input[name*='password']",
        submitButton: "button[type='submit']",
        payerIdLoginLinkRegex: /Payer ID/i,
        forgotPasswordLinkRegex: /Forgot/i,
        signUpLinkRegex: /Register|Sign Up|Create Account/i,
        loginLoadedLog: "✅ Login page loaded successfully",
        fieldsVisibleLog: "✅ Standard login fields are visible",
        switchPayerIdLog: "✅ Successfully switched to Payer ID login view",
        validationLog: "✅ Validation messages displayed correctly",
        passwordToggleFoundLog: "✅ Password visibility toggle found",
        passwordToggleNotFoundLog: "⚠️ No password toggle found",
        navigationLinksLog: "✅ Navigation links for password recovery and registration are present"
    },
    forgotPassword: {
        pageUrl: "https://taxporta.fctirs.gov.ng/forgot-password",
        titleRegex: /Forgot Password|Reset Password|Recover/i,
        emailInput: "input[type='email'], input[name*='email']",
        submitButton: "button[type='submit']",
        backToLoginLinkRegex: /Back to Login|Sign In|Return/i,
        testEmail: "testuser@example.com",
        pageLoadedLog: "✅ Forgot Password page loaded successfully",
        emailPresentLog: "✅ Email input field is present and active",
        buttonVisibleLog: "✅ Reset button is visible",
        validationLog: "✅ Validation for empty email field is working",
        emailEntryLog: "✅ Email can be entered into the input field",
        backLinkLog: "✅ 'Back to Login' link found"
    },
    loginTin: {
        pageUrl: "https://taxporta.fctirs.gov.ng/login-tin",
        titleRegex: /TIN|Tax Identification Number|Login/i,
        tinInput: "input[name*='tin'], input[placeholder*='TIN'], input[type='text']",
        submitButton: "button[type='submit']",
        backToLoginLinkRegex: /Back to Login|Sign In|Email|Payer ID/i,
        testTin: "1234567890",
        pageLoadedLog: "✅ TIN Login page loaded successfully",
        inputActiveLog: "✅ TIN input field is present and active",
        buttonVisibleLog: "✅ Submit button is visible",
        validationLog: "✅ Validation for empty TIN field is working",
        tinEntryLog: "✅ TIN can be entered into the input field",
        backLinkLog: "✅ 'Back to Login' or alternative login link found",
        backLinkNotFoundLog: "⚠️ No obvious link back to main login found."
    },
    loginPayerId: {
        pageUrl: "https://taxporta.fctirs.gov.ng/login",
        payerIdLinkRegex: /Login with Payer ID/i,
        payerIdInput: "input[type='text'], input[name='payerId'], input[placeholder*='payer'], input[placeholder*='ID']",
        submitButton: "button[type='submit'], button:contains('Continue'), button:contains('Submit'), button:contains('Login')",
        testPayerId: "1234567890",
        linkClickedLog: "Payer ID login link clicked",
        inputFoundLog: "Payer ID input field found",
        typedLog: "Typed Payer ID successfully",
        buttonFoundLog: "Submit button found",
        successLog: "Successfully moved to next step or logged in",
        loginPageCheckLog: "Still on login page - checking for changes"
    },
    dashboarddonations: {
        pageUrl01: "/dashboard/donations",
        waitcode01: 2000,
        message01: "body",
        message02: "be.visible",
        message03: "✅ Dashboard donations page loaded",
        message04: "/login",
        message05: "✅ Donations page correctly redirects to login (authentication required)",
        message06: "/donations",
        message07: "✅ Donations page loaded successfully",
        message08: "donation",
        message09: "charity",
        message10: "give",
        message11: "contribute",
        message12: "Page content: ${bodyText}",
        message13: "✅ Page contains donation-related content",
        message14: "❌ No donation-related content found",
        message15: "⚠️ Unexpected URL: ${url}",
    }
};
